server:
  port: 8080
spring:
  application:
    name: main
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/devteria
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: 9TnKrugrHJNqf85He07ZssTEg2lb+d6+087I/hsDQn7zEc62Ju+PJOUBlKG1iPZrjpNyGVlT44/g3S3182cYnQ==
  expirationMs: 3600000
  signerKey:

